### ISSUE TITLE
Inheritance issues while building

### ISSUE THREAD

**Issue by geist-tea** [diamondburned/handy#3]
```
go/src/github.com/diamondburned/handy/handy_generated.go:40:5: cannot use (*glib.Object)(nil) (type *glib.Object) as type objector in assignment:
        *glib.Object does not implement objector (wrong type for Connect method)
                have Connect(string, interface {}, ...interface {}) (glib.SignalHandle, error)
                want Connect(string, interface {}) glib.SignalHandle
go/src/github.com/diamondburned/handy/handy_generated.go:703:4: cannot use &gtk.Widget literal (type *gtk.Widget) as type Caster in field value:
        *gtk.Widget does not implement Caster (wrong type for Connect method)
                have Connect(string, interface {}, ...interface {}) (glib.SignalHandle, error)
                want Connect(string, interface {}) glib.SignalHandle
go/src/github.com/diamondburned/handy/handy_generated.go:1176:4: cannot use &gtk.Widget literal (type *gtk.Widget) as type Caster in field value:
        *gtk.Widget does not implement Caster (wrong type for Connect method)
                have Connect(string, interface {}, ...interface {}) (glib.SignalHandle, error)
                want Connect(string, interface {}) glib.SignalHandle
go/src/github.com/diamondburned/handy/handy_generated.go:2056:4: cannot use &gtk.Widget literal (type *gtk.Widget) as type Caster in field value:
        *gtk.Widget does not implement Caster (wrong type for Connect method)
                have Connect(string, interface {}, ...interface {}) (glib.SignalHandle, error)
                want Connect(string, interface {}) glib.SignalHandle
go/src/github.com/diamondburned/handy/handy_generated.go:2917:3: cannot use &gtk.Widget literal (type *gtk.Widget) as type Caster in field value:
        *gtk.Widget does not implement Caster (wrong type for Connect method)
                have Connect(string, interface {}, ...interface {}) (glib.SignalHandle, error)
                want Connect(string, interface {}) glib.SignalHandle
```

**Comment by diamondburned** [comment]
This is caused by PR https://github.com/gotk3/gotk3/pull/706.

A fix would be to either rollback to previous `handy` commits or replace `gotk3` with the version the code was changed to:

```
replace github.com/gotk3/gotk3 => github.com/diamondburned/gotk3 v0.0.0-20201229054305-848200601f20
```

**Comment by diamondburned** [comment]
Tacking this issue here because it's part of the problem: https://github.com/golang/go/issues/30354
